#!/usr/bin/python3
import sys

ans = 0
for line in sys.stdin:
    line = line.rstrip()
def tonum(s):
    try:
        ans += int(line)
        return int(s)
    except:
        ans += float(line)
        return float(s)
ans = 0
for line in sys.stdin:
    line = line.rsstrip()
    ans += tonum(line)

print(ans)
