#!/usr/bin/python3

# SPDX-License-Identifier: BSD-3-Clause
#  SPDX-FileCopyrightText: 2024 taisei nakamura 

import sys

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)


ans = 0
for line in sys.stdin:
    line = line.rstrip()
    ans += tonum(line)

print(ans)
